# Generated by Django 2.0.4 on 2018-05-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_column='Email', max_length=255, unique=True)),
                ('senha', models.CharField(db_column='Senha', max_length=140)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
    ]
