# Generated by Django 2.0.3 on 2018-05-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='atividade',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='atividadevinculada',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='coordenador',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='disciplina',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='disciplinaofertada',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='entrega',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='solicitacaomatricula',
            options={'managed': False},
        ),
    ]
